from typing import List, Protocol

from app.contracts import AttackChain, DetectionResult, Evidence, Session, UnifiedSecurityEvent


class EventRepository(Protocol):
    def append_events(self, events: List[UnifiedSecurityEvent]) -> int: ...
    def list_events(self, limit: int = 100) -> List[UnifiedSecurityEvent]: ...


class AnalysisRepository(EventRepository, Protocol):
    def put_evidence(self, evidence: List[Evidence]) -> int: ...
    def put_sessions(self, sessions: List[Session]) -> int: ...
    def put_detections(self, detections: List[DetectionResult]) -> int: ...
    def put_chains(self, chains: List[AttackChain]) -> int: ...

