/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Detail */
        get: operations["evidence_detail_api_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detections */
        get: operations["detections_api_detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chains */
        get: operations["chains_api_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain */
        get: operations["chain_api_chains__chain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Slice */
        get: operations["graph_slice_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entities */
        get: operations["entities_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hosts */
        get: operations["hosts_api_hosts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Network */
        get: operations["network_api_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attack */
        get: operations["attack_api_attack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attribution */
        get: operations["attribution_api_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports */
        get: operations["reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ActorContext */
        ActorContext: {
            /** @default null */
            user: components["schemas"]["EntityRef"] | null;
            /** @default null */
            process: components["schemas"]["EntityRef"] | null;
            /** @default null */
            parent_process: components["schemas"]["EntityRef"] | null;
        };
        /** AgentConstraints */
        AgentConstraints: {
            /**
             * Max Steps
             * @default 8
             */
            max_steps: number;
            /**
             * Deadline Ms
             * @default 60000
             */
            deadline_ms: number;
            /**
             * Read Only
             * @default true
             */
            read_only: boolean;
        };
        /** AgentFinding */
        AgentFinding: {
            /** Claim */
            claim: string;
            /** Confidence */
            confidence: number;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Alternatives */
            alternatives?: string[];
        };
        /** AgentResult */
        AgentResult: {
            /** Result Id */
            result_id: string;
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "partial" | "failed";
            /** Findings */
            findings?: components["schemas"]["AgentFinding"][];
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallSummary"][];
            /** Output Refs */
            output_refs?: string[];
            /** Errors */
            errors?: components["schemas"]["StructuredError"][];
            model_info: components["schemas"]["ModelInfo"];
        };
        /** AgentTask */
        AgentTask: {
            /** Task Id */
            task_id: string;
            /** Case Id */
            case_id: string;
            /**
             * Agent Role
             * @enum {string}
             */
            agent_role: "coordinator" | "host" | "network" | "correlation" | "attribution" | "report";
            /** Objective */
            objective: string;
            /** Input Refs */
            input_refs?: string[];
            /** Allowed Tools */
            allowed_tools?: string[];
            constraints?: components["schemas"]["AgentConstraints"];
            /**
             * Parent Task Id
             * @default null
             */
            parent_task_id: string | null;
            /**
             * State
             * @default queued
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** Alert */
        Alert: {
            /** Alert Id */
            alert_id: string;
            /** Detection Id */
            detection_id: string;
            /**
             * Case Id
             * @default null
             */
            case_id: string | null;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "acknowledged" | "investigating" | "closed" | "suppressed";
            /**
             * Assignee
             * @default null
             */
            assignee: string | null;
            /**
             * Disposition
             * @default unknown
             * @enum {string}
             */
            disposition: "true_positive" | "false_positive" | "benign_positive" | "unknown";
            /** Analyst Notes */
            analyst_notes?: components["schemas"]["Note"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AttackChain */
        AttackChain: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Chain Id */
            chain_id: string;
            /** Run Id */
            run_id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @default candidate
             * @enum {string}
             */
            status: "candidate" | "confirmed" | "dismissed";
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** @default null */
            entry_point: components["schemas"]["ChainStepRef"] | null;
            /** Steps */
            steps: components["schemas"]["ChainStep"][];
            /** Entity Ids */
            entity_ids?: string[];
            /** Detection Ids */
            detection_ids?: string[];
            /** Technique Ids */
            technique_ids?: string[];
            /** Score */
            score: number;
            /** Completeness */
            completeness: number;
            /** Uncertainties */
            uncertainties?: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Algorithm Version */
            algorithm_version: string;
        };
        /** AttackMapping */
        AttackMapping: {
            /** Technique Id */
            technique_id: string;
            /**
             * Subtechnique Id
             * @default null
             */
            subtechnique_id: string | null;
            /** Tactic Ids */
            tactic_ids: string[];
            /** Mapping Rule Id */
            mapping_rule_id: string;
            /** Attack Version */
            attack_version: string;
            /** Confidence */
            confidence: number;
        };
        /** ChainStep */
        ChainStep: {
            /** Step Id */
            step_id: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "initial_access" | "execution" | "persistence" | "privilege_escalation" | "credential_access" | "discovery" | "lateral_movement" | "collection" | "command_and_control" | "exfiltration";
            /** Tactic Id */
            tactic_id: string;
            /** Technique Id */
            technique_id: string;
            /** Event Ids */
            event_ids?: string[];
            /** Detection Ids */
            detection_ids?: string[];
            /** Entity Ids */
            entity_ids?: string[];
            /** Session Ids */
            session_ids?: string[];
            /** Predecessors */
            predecessors?: components["schemas"]["StepPredecessor"][];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Score */
            score: number;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Explanation */
            explanation: string;
        };
        /** ChainStepRef */
        ChainStepRef: {
            /** Step Id */
            step_id: string;
            /** Stage */
            stage: string;
        };
        /** DetectionResult */
        DetectionResult: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Detection Id */
            detection_id: string;
            /** Run Id */
            run_id: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            /** Title */
            title: string;
            /**
             * Detector Type
             * @enum {string}
             */
            detector_type: "rule" | "threshold" | "statistical" | "correlation";
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "suppressed" | "confirmed" | "false_positive";
            /**
             * Severity
             * @enum {string}
             */
            severity: "informational" | "low" | "medium" | "high" | "critical";
            /** Confidence */
            confidence: number;
            /** Event Ids */
            event_ids: string[];
            /** Entity Ids */
            entity_ids?: string[];
            /** Session Ids */
            session_ids?: string[];
            /** Feature Values */
            feature_values?: Record<string, never>;
            /** Reason */
            reason: string;
            /** Attack Mappings */
            attack_mappings?: components["schemas"]["AttackMapping"][];
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntityRef */
        EntityRef: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "host" | "user" | "process" | "file" | "registry" | "ip" | "domain" | "session" | "c2";
            /** Entity Id */
            entity_id: string;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Display Name
             * @default null
             */
            display_name: string | null;
            /** Attributes */
            attributes?: Record<string, never>;
            /**
             * Identity Quality
             * @default provisional
             * @enum {string}
             */
            identity_quality: "exact" | "derived" | "provisional";
        };
        /** EventProvenance */
        EventProvenance: {
            /** Raw Id */
            raw_id: string;
            /** Raw Ref */
            raw_ref: string;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Parser Name */
            parser_name: string;
            /** Parser Version */
            parser_version: string;
            /** Mapping Warnings */
            mapping_warnings?: string[];
        };
        /** Evidence */
        Evidence: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "raw_event" | "normalized_event" | "graph_fact" | "intel_fact" | "analytic";
            /** Source Ref */
            source_ref: string;
            /** Event Ids */
            event_ids?: string[];
            /** Entity Ids */
            entity_ids?: string[];
            /**
             * Excerpt
             * @default null
             */
            excerpt: unknown | null;
            /**
             * Observed At
             * @default null
             */
            observed_at: string | null;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Producer */
            producer: string;
            /** Producer Version */
            producer_version: string;
            /**
             * Integrity Sha256
             * @default null
             */
            integrity_sha256: string | null;
            /**
             * Reliability
             * @enum {string}
             */
            reliability: "direct" | "corroborated" | "derived" | "external_unverified";
            /** Supports */
            supports?: string[];
            /** Contradicts */
            contradicts?: string[];
        };
        /** GraphEntity */
        GraphEntity: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "host" | "user" | "process" | "file" | "registry" | "ip" | "domain" | "session" | "alert" | "technique" | "c2" | "evidence";
            /** Labels */
            labels?: string[];
            /**
             * Display Name
             * @default null
             */
            display_name: string | null;
            /** Properties */
            properties?: Record<string, never>;
            /**
             * First Seen
             * @default null
             */
            first_seen: string | null;
            /**
             * Last Seen
             * @default null
             */
            last_seen: string | null;
            /**
             * Identity Quality
             * @default provisional
             * @enum {string}
             */
            identity_quality: "exact" | "derived" | "provisional";
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** GraphRelation */
        GraphRelation: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Relation Id */
            relation_id: string;
            /** Relation Type */
            relation_type: string;
            /** Source Entity Id */
            source_entity_id: string;
            /** Target Entity Id */
            target_entity_id: string;
            /**
             * Start Time
             * @default null
             */
            start_time: string | null;
            /**
             * End Time
             * @default null
             */
            end_time: string | null;
            /** Properties */
            properties?: Record<string, never>;
            /** Confidence */
            confidence: number;
            /**
             * Derived
             * @default false
             */
            derived: boolean;
            /** Event Ids */
            event_ids?: string[];
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** ModelInfo */
        ModelInfo: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /** NetworkContext */
        NetworkContext: {
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
            /**
             * Direction
             * @default unknown
             * @enum {string}
             */
            direction: "inbound" | "outbound" | "lateral" | "unknown";
            /**
             * Transport
             * @default null
             */
            transport: ("tcp" | "udp" | "icmp" | "other") | null;
            /**
             * Application
             * @default null
             */
            application: ("dns" | "http" | "https" | "ssh" | "smb" | "rdp" | "smtp" | "other") | null;
            src?: components["schemas"]["NetworkEndpoint"];
            dst?: components["schemas"]["NetworkEndpoint"];
            /**
             * Bytes Sent
             * @default null
             */
            bytes_sent: number | null;
            /**
             * Bytes Received
             * @default null
             */
            bytes_received: number | null;
            /**
             * Packets Sent
             * @default null
             */
            packets_sent: number | null;
            /**
             * Packets Received
             * @default null
             */
            packets_received: number | null;
            /**
             * Duration Ms
             * @default null
             */
            duration_ms: number | null;
            /**
             * Zeek Uid
             * @default null
             */
            zeek_uid: string | null;
            /**
             * Dns
             * @default null
             */
            dns: Record<string, never> | null;
            /**
             * Http
             * @default null
             */
            http: Record<string, never> | null;
            /**
             * Icmp
             * @default null
             */
            icmp: Record<string, never> | null;
        };
        /** NetworkEndpoint */
        NetworkEndpoint: {
            /**
             * Ip
             * @default null
             */
            ip: string | null;
            /**
             * Port
             * @default null
             */
            port: number | null;
            /**
             * Host Id
             * @default null
             */
            host_id: string | null;
        };
        /** Note */
        Note: {
            /** Author */
            author: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ObjectContext */
        ObjectContext: {
            /**
             * Type
             * @default null
             */
            type: ("process" | "file" | "registry" | "user" | "host" | "network" | "memory" | "service" | "other") | null;
            /** @default null */
            ref: components["schemas"]["EntityRef"] | null;
        };
        /** RawEventEnvelope */
        RawEventEnvelope: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Raw Id */
            raw_id: string;
            source: components["schemas"]["SourceDescriptor"];
            /**
             * Source Record Id
             * @default null
             */
            source_record_id: string | null;
            /**
             * Event Time Raw
             * @default null
             */
            event_time_raw: string | number | null;
            /**
             * Observed Time
             * Format: date-time
             */
            observed_time: string;
            /**
             * Ingested Time
             * Format: date-time
             */
            ingested_time: string;
            /**
             * Payload Format
             * @enum {string}
             */
            payload_format: "json" | "text" | "xml" | "csv" | "pcap_ref";
            /**
             * Payload
             * @default null
             */
            payload: Record<string, never> | string | null;
            /** Raw Ref */
            raw_ref: string;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Labels */
            labels?: Record<string, never>;
        };
        /** Session */
        Session: {
            /** Session Id */
            session_id: string;
            /**
             * Session Type
             * @enum {string}
             */
            session_type: "login" | "network";
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * @default null
             */
            end_time: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "active" | "closed" | "timed_out" | "orphan_start" | "orphan_end";
            /**
             * Host Id
             * @default null
             */
            host_id: string | null;
            /**
             * User Id
             * @default null
             */
            user_id: string | null;
            /**
             * Src Ip
             * @default null
             */
            src_ip: string | null;
            /**
             * Dst Ip
             * @default null
             */
            dst_ip: string | null;
            /**
             * Protocol
             * @default null
             */
            protocol: string | null;
            /** Source Event Ids */
            source_event_ids?: string[];
            /** Confidence */
            confidence: number;
        };
        /** SourceDescriptor */
        SourceDescriptor: {
            kind: components["schemas"]["SourceKind"];
            /** Product */
            product: string;
            /**
             * Dataset
             * @default null
             */
            dataset: string | null;
            /** Sensor Id */
            sensor_id: string;
            /**
             * Host Hint
             * @default null
             */
            host_hint: string | null;
            /**
             * Source Record Id
             * @default null
             */
            source_record_id: string | null;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "wazuh" | "sysmon" | "windows_security" | "auditd" | "zeek" | "dataset" | "firewall" | "application";
        /** StepPredecessor */
        StepPredecessor: {
            /** Step Id */
            step_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "temporal" | "spawn" | "same_session" | "authentication" | "network_flow" | "file_lineage" | "identity_change" | "analyst_link";
            /** Score */
            score: number;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** StructuredError */
        StructuredError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** TimeContext */
        TimeContext: {
            /**
             * Original
             * @default null
             */
            original: string | number | null;
            /**
             * Clock Offset Ms
             * @default null
             */
            clock_offset_ms: number | null;
            /**
             * Uncertainty Ms
             * @default 0
             */
            uncertainty_ms: number;
            /**
             * Quality
             * @default unknown
             * @enum {string}
             */
            quality: "synced" | "estimated" | "unsynced" | "unknown";
        };
        /** ToolCallSummary */
        ToolCallSummary: {
            /** Tool */
            tool: string;
            /** Input Summary */
            input_summary?: Record<string, never>;
            /** Output Refs */
            output_refs?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed" | "denied";
        };
        /** UnifiedSecurityEvent */
        UnifiedSecurityEvent: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Event Id */
            event_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Observed Time
             * Format: date-time
             */
            observed_time: string;
            /**
             * Ingested Time
             * Format: date-time
             */
            ingested_time: string;
            time: components["schemas"]["TimeContext"];
            source: components["schemas"]["SourceDescriptor"];
            /** @default null */
            host: components["schemas"]["EntityRef"] | null;
            actor?: components["schemas"]["ActorContext"];
            object?: components["schemas"]["ObjectContext"];
            /** @default null */
            network: components["schemas"]["NetworkContext"] | null;
            /** Action */
            action: string;
            /** Event Type */
            event_type: string;
            /**
             * Outcome
             * @default unknown
             * @enum {string}
             */
            outcome: "success" | "failure" | "unknown";
            /**
             * Severity
             * @default unknown
             * @enum {string}
             */
            severity: "informational" | "low" | "medium" | "high" | "critical" | "unknown";
            /**
             * Message
             * @default null
             */
            message: string | null;
            /** Tags */
            tags?: string[];
            /** Extensions */
            extensions?: Record<string, never>;
            provenance: components["schemas"]["EventProvenance"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_evidence_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_detail_api_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detections_api_detections_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    chains_api_chains_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_api_chains__chain_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_slice_api_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    entities_api_entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    hosts_api_hosts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    network_api_network_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    attack_api_attack_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    attribution_api_attribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    reports_api_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    health_api_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    version_api_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
