import { Link } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { useAnalysis } from '../context/AnalysisContext'
import { useApi } from '../hooks/useApi'
import { attributionStatusName, pct } from '../lib/display'

interface Candidate {case_id:string;chain_id:string;status:string;candidate?:string;group?:string;similarity?:number;technique_overlap?:string[];c2_ioc_evidence?:string[];supporting_evidence?:string[];counter_evidence?:string[];confidence?:number}

export function AttributionPage(){const {currentRunId:runId,runScopedPath}=useAnalysis();const suffix=runId?`?run_id=${encodeURIComponent(runId)}`:'';const {data,loading,error,meta}=useApi<Candidate[]>(`/api/attribution${suffix}`);return <><PageHeader title="归因候选 / 相似性分析" description="当前 run 的 Agent Attribution 结果；只表示证据约束下的相似性分析。" aside={runId ? <span className="freshness">任务 {runId}</span> : undefined}/>{loading&&<div className="skeleton-list"><span/><span/></div>}{error&&<EmptyState kind="error" title="归因结果读取失败" detail={error}/>} {!loading&&!error&&!data?.length&&<EmptyState title="尚无归因候选" detail={meta?.warnings[0]??'完成 Agent 调查后，候选与无法归因结论会显示在这里。'}/>}<div className="attribution-grid">{data?.map((item,index)=>{const techniqueOverlap=item.technique_overlap??[];const c2Evidence=item.c2_ioc_evidence??[];const supportingEvidence=item.supporting_evidence??[];const counterEvidence=item.counter_evidence??[];const candidateName=item.candidate??item.group??'无法可靠归因';const confidence=item.confidence??0;const similarity=item.similarity??0;return <article className="attribution-card panel" key={`${item.case_id}-${index}`}><header><div><span className="eyebrow">{attributionStatusName[item.status] ?? '候选相似性分析'}</span><h2>{candidateName}</h2></div><strong title="结论置信度只表示与离线 ATT&CK/工具/C2 特征的相似性，不代表身份确认。">{pct(confidence)}<small>结论置信度</small></strong></header><dl><div><dt title="相似度来自 Technique、工具、基础设施等特征重合，不是攻击者身份概率。">相似度</dt><dd>{pct(similarity)}</dd></div><div><dt>Technique 重合</dt><dd>{techniqueOverlap.join(' · ')||'—'}</dd></div></dl><h3>C2 / IOC 证据</h3><div className="evidence-links">{c2Evidence.map(id=><Link key={id} to={runScopedPath('/chains',{chain:item.chain_id,evidence:id})}>{id}</Link>)}{!c2Evidence.length&&<span>无候选专属 IOC</span>}</div><h3>支持证据</h3><div className="evidence-links">{supportingEvidence.map(id=><Link key={id} to={runScopedPath('/chains',{chain:item.chain_id,evidence:id})}>{id}</Link>)}{!supportingEvidence.length&&<span>暂无支持证据引用</span>}</div><h3>反证 / 限制</h3>{counterEvidence.length?counterEvidence.map(value=><p className="counter" key={value}>{value}</p>):<p className="counter">暂无反证记录；该页面仍只表示候选相似性，不代表身份确认。</p>}<footer><Link to={runScopedPath('/agents',{case:item.case_id})}>查看 Agent 调查</Link><Link to={runScopedPath('/chains',{chain:item.chain_id})}>查看攻击链</Link></footer></article>})}</div></>}
