import { ResourcePage } from '../components/ResourcePage'

export const IncidentsPage=()=> <ResourcePage title="攻击事件中心" description="审阅确定性检测、置信度、ATT&CK 映射与证据数量。" endpoint="/api/detections" columns={[["title","事件"],["severity","严重度"],["confidence","置信度"],["attack_mappings.0.subtechnique_id|attack_mappings.0.technique_id","ATT&CK"],["rule_id","规则"],["created_at","发生时间"]]}/>
export const GraphPage=()=> <ResourcePage title="安全知识图谱" description="查看规范化实体与有证据引用的行为关系。" endpoint="/api/entities" columns={[["display_name","实体"],["entity_type","类型"],["first_seen","首次出现"],["last_seen","最后出现"]]}/>
export const HostsPage=()=> <ResourcePage title="主机行为分析" description="围绕登录会话、进程树、文件、注册表、权限和内存行为调查。" endpoint="/api/hosts" columns={[["hostname","主机"],["logins","登录"],["process","进程"],["file","文件"],["registry","注册表"],["privilege","权限"],["memory","内存"],["last_seen","最后活动"]]}/>
export const NetworkPage=()=> <ResourcePage title="网络流量分析" description="按 Zeek UID 与五元组检查 DNS、HTTP、ICMP、C2 和跨源会话。" endpoint="/api/network" columns={[["event_time","时间"],["source","来源"],["action","动作"],["transport","协议"],["application","应用"],["src","源端"],["dst","目标端"],["bytes_sent","发送字节"]]}/>
export const EventsPage=()=> <ResourcePage title="日志与安全事件" description="检索统一事件并沿 provenance 回查原始记录。" endpoint="/api/events" columns={[["event_time","事件时间"],["source.kind","来源"],["host.display_name","主机"],["action","动作"],["event_type","类型"],["message","摘要"],["provenance.parser_name","解析器"]]}/>
export const AttackPage=()=> <ResourcePage title="ATT&CK 分析" description="查看固定版本的 Technique 覆盖、映射规则与证据数量。" endpoint="/api/attack" columns={[["technique_id","Technique"],["detection_count","检测"],["evidence_count","证据"],["attack_version","版本"]]}/>
export const SourcesPage=()=> <ResourcePage title="数据源与资产" description="检查传感器、最后事件、时间质量、dead-letter 与资产覆盖。" endpoint="/api/sources" columns={[["sensor_id","传感器"],["kind","来源"],["dataset","数据集"],["status","状态"],["last_event_time","最后事件"]]}/>
export const DatasetsPage=()=> <ResourcePage title="数据集实验" description="公开攻击数据集通过同一主管道导入并与 Ground Truth 对比。" endpoint="/api/datasets" columns={[["dataset_id","数据集"],["status","状态"],["records","记录数"],["mapping_rate","映射率"],["f1","F1"]]}/>
