import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiGet } from '../api/client'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { useAnalysis } from '../context/AnalysisContext'
import { useApi } from '../hooks/useApi'

interface Report {report_id:string;case_id:string;run_id:string;format:string;version:string;created_at:string;evidence_ids:string[];attack_chain?:string;agent_investigation:string;export_url:string}
interface ReportDetail extends Report {content:string;sections?:Record<string,unknown>}

export function ReportsPage(){const {currentRunId:runId,runScopedPath}=useAnalysis();const suffix=runId?`?run_id=${encodeURIComponent(runId)}`:'';const {data,loading,error,meta}=useApi<Report[]>(`/api/reports${suffix}`);const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<ReportDetail|null>(null);useEffect(()=>{setSelected(null);setDetail(null)},[runId]);useEffect(()=>{if(selected&&data&&!data.some(item=>item.report_id===selected)){setSelected(null);setDetail(null);return}if(!selected&&data?.length)setSelected(data[0].report_id)},[data,selected]);useEffect(()=>{if(selected)apiGet<ReportDetail>(`/api/reports/${selected}`).then(value=>setDetail(value.data))},[selected]);return <><PageHeader title="报告中心" description="当前 run 的 Report；可沿 Evidence、AttackChain 与 Agent 调查来源下钻。" aside={runId ? <span className="freshness">任务 {runId}</span> : undefined}/>{loading&&<div className="skeleton-list"><span/><span/></div>}{error&&<EmptyState kind="error" title="报告读取失败" detail={error}/>} {!loading&&!error&&!data?.length&&<EmptyState title="尚无调查报告" detail={meta?.warnings[0]??'Report Agent 完成运行后，持久化报告会出现在这里。'}/>} {!!data?.length&&<div className="report-workspace"><aside className="report-list panel">{data.map(item=><button className={selected===item.report_id?'selected':''} onClick={()=>setSelected(item.report_id)} key={item.report_id}><span className="format-tag">{item.format}</span><strong>{item.report_id}</strong><small>{new Date(item.created_at).toLocaleString('zh-CN')}</small></button>)}</aside>{detail&&<article className="report-view panel"><header><div><span className="eyebrow">{detail.format} · v{detail.version}</span><h2>Agent 调查报告</h2></div><a className="primary-action" href={detail.export_url}>导出 {detail.format==='html'?'HTML':'Markdown'}</a></header><nav><Link to={runScopedPath('/agents',{case:detail.agent_investigation})}>Agent 调查来源</Link>{detail.attack_chain&&<Link to={runScopedPath('/chains',{chain:detail.attack_chain})}>AttackChain</Link>}<span>{detail.evidence_ids.length} 条 Evidence</span></nav>{detail.sections?<div className="report-sections">{Object.entries(detail.sections).map(([title,value])=><section key={title}><h3>{title}</h3><pre>{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre></section>)}</div>:<pre>{detail.content}</pre>}<div className="evidence-links">{detail.evidence_ids.map(id=><Link key={id} to={runScopedPath('/chains',{chain:detail.attack_chain,evidence:id})}>{id}</Link>)}</div></article>}</div>}</>}
